require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.1

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/SignalException:
  Exclude:
    - 'app/concepts/**/*'

Lint/UnreachableCode:
  Exclude:
    - 'app/concepts/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'config/application.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
