default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: todo_list_api_trb_development
  user: <%= Rails.application.credentials[:pguser] %>
  password: <%= Rails.application.credentials[:pgpass] %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: 5432

test:
  <<: *default
  adapter: postgresql
  database: todo_list_api_trb_test
  user: <%= Rails.application.credentials[:pguser] %>
  password: <%= Rails.application.credentials[:pgpass] %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: 5432

production:
  <<: *default
  database: todo_list_api_trb_production
  user: <%= Rails.application.credentials[:pguser] %>
  password: <%= Rails.application.credentials[:pgpass] %>
